import Head from "next/head"
import Header from "./Header"

const Layout = () => {
  return (
    <>
      <Head>
        <title>Xiaobo's Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
    </>
  )
}

export default Layout
