import React from "react"
import Head from "next/head"
import Header from "./Header"

const Layout = ({ children }: { children: React.ReactNode }) => {
  return (
    <div>
      <Head>
        <title>Xiaobo's Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="px-5 mt-12">
        <div className=" max-w-[700px] m-auto pb-8">{children}</div>
      </main>
    </div>
  )
}

export default Layout
